FROM mcr.microsoft.com/mssql/server:2022-latest

#ADD entrypoint.sh /

# sql tools setup;
# sqlcmd -S <host> -U <user> -P <password>
#RUN \
#    apt-get update && \
#    apt-get install -y curl apt-transport-https
#    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
#    curl https://packages.microsoft.com/config/ubuntu/15.10/prod.list | tee /etc/apt/sources.list.d/msprod.list && \
#    apt-get update && \
#    apt-get install -y mssql-tools && \
#    chmod +x /entrypoint.sh

#EXPOSE 1433

#ENTRYPOINT ["/entrypoint.sh"]
