FROM mysql:8.0

## Place the dropin config file in the relevant folder
#COPY keyring.cnf /etc/mysql/conf.d/
#
## Create the keyring folder and adapt perms
#RUN mkdir -p /usr/local/mysql/mysql-keyring && \
#    chmod 750 /usr/local/mysql/mysql-keyring && \
#    chown mysql.mysql /usr/local/mysql/mysql-keyring
